### ISSUE TITLE
Automatic image size according to input image ratio does not work

### ISSUE THREAD

**Issue by psykokwak-com** [thomasasfk/sd-webui-aspect-ratio-helper#46] opened 2023-04-10 12:10 UTC
Hello,
Since last few update, the automatic image size based on the input image ratio does not work.
See below :

![gif](https://i.ibb.co/7vrzNxZ/NVIDIA-Share-ue-Mmsf43nk.gif)

And here the javascript error I got : 

```
aspectRatioController.js?1681108525.8360796:430 Uncaught TypeError: Cannot read properties of null (reading 'querySelector')
    at aspectRatioController.js?1681108525.8360796:430:45
    at Array.forEach (<anonymous>)
    at postImageControllerSetupFunction (aspectRatioController.js?1681108525.8360796:428:32)
    at MutationObserver.<anonymous> (aspectRatioController.js?1681108525.8360796:390:17)

aspectRatioController.js?1681108525.8360796:20 Uncaught TypeError: Cannot read properties of null (reading 'textContent')
    at getSelectedImage2ImageTab (aspectRatioController.js?1681108525.8360796:20:85)
    at getCurrentImage (aspectRatioController.js?1681108525.8360796:24:24)
    at AspectRatioController.setAspectRatio (aspectRatioController.js?1681108525.8360796:321:25)
    at HTMLSelectElement.<anonymous> (aspectRatioController.js?1681108525.8360796:118:24)
```

**Comment by thomasasfk** [comment] 2023-04-10 18:10
Huh, thanks for reporting.  Seems this line is throwing the error:

https://github.com/thomasasfk/sd-webui-aspect-ratio-helper/blob/ab303d6e979e9d916850ea609b621345a9cb27b8/javascript/aspectRatioController.js#L20

Wonder if the selector is brittle and something on the webui has changed... I'll give it a look.

**Comment by thomasasfk** [comment] 2023-04-10 18:29
I can't seem to reproduce this, does this happen consistently for you?  Wondering if the way the current tab is being grabbed is too brittle for different styles and themes...

**Comment by psykokwak-com** [comment] 2023-04-10 19:41
Here my conf : 

```
venv "C:\Users\Jyce\Desktop\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: a9fed7c364061ae6efb37f797b6b522cb3cf7aa2
```
(Not the latest automatic1111 version)

![conf](https://i.imgur.com/Of0179e.png)

**Comment by thomasasfk** [comment] 2023-04-10 20:01
The way I've done the tab detection is bad anyways, just realised coupling it to English is probably bad for localisations too! I'll look at alternative options.

**Comment by thomasasfk** [comment] 2023-04-10 21:04
@psykokwak-com thanks again for raising this, I've changed some things in https://github.com/thomasasfk/sd-webui-aspect-ratio-helper/pull/47 and merged to main.  

Can you try updating your extension and seeing if your errors are gone? I'm still not sure the root cause of your issue, my guess was that it was a different hierarchy of elements which wasn't being picked up by the following:
https://github.com/thomasasfk/sd-webui-aspect-ratio-helper/blob/ab303d6e979e9d916850ea609b621345a9cb27b8/javascript/aspectRatioController.js#L20

I've since changed it to use the following:
https://github.com/thomasasfk/sd-webui-aspect-ratio-helper/blob/905a8a0ac6ef26eae1ac0e56999bc4507859d84b/javascript/aspectRatioController.js#L18-L21

Which should hopefully resolve your issue.

The styling should also match your light theme now hopefully!

**Comment by psykokwak-com** [comment] 2023-04-11 07:00
Hello @thomasasfk , thanks for your help.
Unfortunately it still not work. The issue remains.

```
aspectRatioController.js?1681195824.9943304:27 Uncaught TypeError: Cannot read properties of null (reading 'querySelector')
    at getCurrentImage (aspectRatioController.js?1681195824.9943304:27:54)
    at AspectRatioController.setAspectRatio (aspectRatioController.js?1681195824.9943304:319:25)
    at HTMLSelectElement.<anonymous> (aspectRatioController.js?1681195824.9943304:116:24)
```

What can I do to help you ?

**Comment by thomasasfk** [comment] 2023-04-11 17:50
> Hello @thomasasfk , thanks for your help. Unfortunately it still not work. The issue remains.
> 
> ```
> aspectRatioController.js?1681195824.9943304:27 Uncaught TypeError: Cannot read properties of null (reading 'querySelector')
>     at getCurrentImage (aspectRatioController.js?1681195824.9943304:27:54)
>     at AspectRatioController.setAspectRatio (aspectRatioController.js?1681195824.9943304:319:25)
>     at HTMLSelectElement.<anonymous> (aspectRatioController.js?1681195824.9943304:116:24)
> ```
> 
> What can I do to help you ?

Out of curiosity - is there any reason you aren't on the latest version of the A1111 webui? Is it because it may break your current workflow due to incompatible changes?

**Closed** 2023-05-22 15:45 UTC
